name: Lay Lai Key
on: workflow_dispatch

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Giai ma Key
        run: |
          echo "------ COPY TU DAY ------"
          echo "R2_ACCESS_KEY_ID base64:"
          echo -n "${{ secrets.R2_ACCESS_KEY_ID }}" | base64
          
          echo "R2_SECRET_ACCESS_KEY base64:"
          echo -n "${{ secrets.R2_SECRET_ACCESS_KEY }}" | base64

          echo "SUPABASE_URL base64:"
          echo -n "${{ secrets.SUPABASE_URL }}" | base64
          
          echo "SUPABASE_SERVICE_ROLE_KEY base64:"
          echo -n "${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" | base64
          
          echo "PROXY_WORKER_URL base64:"
          echo -n "${{ secrets.PROXY_WORKER_URL }}" | base64
          
          echo "BINANCE_INTERNAL_AGG_API base64:"
          echo -n "${{ secrets.BINANCE_INTERNAL_AGG_API }}" | base64
          
          echo "BINANCE_INTERNAL_KLINES_API base64:"
          echo -n "${{ secrets.BINANCE_INTERNAL_KLINES_API }}" | base64
          
          echo "R2_ENDPOINT_URL base64:"
          echo -n "${{ secrets.R2_ENDPOINT_URL }}" | base64
          
          echo "R2_BUCKET_NAME base64:"
          echo -n "${{ secrets.R2_BUCKET_NAME }}" | base64
          echo "------ DEN DAY ------"
